# Generated by Django 4.0.6 on 2022-07-27 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('miniblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 14, 14, 25, 619208, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
