# Generated by Django 4.0.6 on 2022-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblogapp', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos'),
        ),
    ]
